const actionLabels: Record<string, string> = {
  add_admin_role: "新增管理员授权",
  approve_post: "审核通过发布",
  change_admin_role: "调整管理员权限",
  contact_issue: "联系方式问题提醒",
  content_issue: "内容问题提醒",
  create_ad: "新增广告",
  create_default_home_sections: "创建默认首页模块",
  create_default_latest_ticker: "创建默认最新动态配置",
  create_default_navigation_categories: "创建默认导航分类",
  create_default_news_categories: "创建默认新闻分类",
  create_default_top_quick_links: "创建默认顶部快捷导航",
  create_latest_ticker: "新增手动动态",
  create_navigation_category: "新增导航分类",
  create_navigation_link: "新增导航网站",
  create_news_category: "新增新闻分类",
  create_news_post: "新增新闻",
  create_notification: "创建通知",
  create_top_quick_link: "新增顶部快捷导航",
  delete_latest_ticker: "删除手动动态",
  delete_post: "删除发布",
  delete_top_quick_link: "删除顶部快捷导航",
  disable_admin: "停用管理员",
  disable_latest_ticker: "停用手动动态",
  disable_top_quick_link: "停用顶部快捷导航",
  duplicate_post: "重复发布提醒",
  enable_latest_ticker: "启用手动动态",
  enable_top_quick_link: "启用顶部快捷导航",
  handle_report: "处理举报",
  hide_navigation_category: "隐藏导航分类",
  hide_navigation_link: "隐藏导航网站",
  hide_post: "下架发布",
  image_issue: "图片问题提醒",
  mark_feedback_viewed: "标记反馈已查看",
  mark_image_asset_deleted: "标记图片已删除",
  mark_post_pending_review: "标记待审核",
  missing_info: "需要补充信息提醒",
  move_latest_posts_section: "调整最新发布排序",
  move_latest_ticker: "调整手动动态排序",
  move_latest_ticker_section: "调整自动动态排序",
  move_top_quick_link: "调整顶部快捷导航排序",
  notify_author: "通知作者",
  permanently_delete_news: "永久删除新闻",
  permanently_delete_navigation_link: "永久删除导航网站",
  permanently_delete_post: "永久删除发布",
  pin_news_post: "置顶新闻",
  publish_post: "恢复显示发布",
  purge_feedback: "永久删除反馈",
  purge_report: "永久删除举报",
  reject_post: "审核未通过",
  remove_ad_image: "删除广告图片",
  remove_home_banner_image: "删除首页 Banner 图片",
  reopen_report: "重新打开举报",
  restore_admin: "恢复管理员",
  restore_feedback: "恢复反馈",
  restore_navigation_link: "恢复导航网站",
  restore_news_from_recycle_bin: "从回收站恢复新闻",
  restore_post_from_recycle_bin: "从回收站恢复发布",
  restore_report: "恢复举报",
  set_news_deleted: "删除新闻",
  set_news_draft: "保存新闻草稿",
  set_news_hidden: "隐藏新闻",
  set_news_published: "发布新闻",
  soft_delete_ad: "删除广告",
  soft_delete_feedback: "删除反馈",
  soft_delete_navigation_link: "删除导航网站",
  soft_delete_report: "删除举报",
  sort_navigation_categories: "调整导航分类排序",
  toggle_ad_active: "切换广告启用状态",
  unpin_news_post: "取消置顶新闻",
  update_ad: "编辑广告",
  update_admin_role: "编辑管理员授权",
  update_home_section: "更新首页模块",
  update_latest_posts_section: "更新最新发布模块",
  update_latest_ticker: "编辑手动动态",
  update_latest_ticker_global_settings: "更新最新动态全局设置",
  update_latest_ticker_sections: "更新自动动态设置",
  update_navigation_category: "编辑导航分类",
  update_navigation_category_display_limit: "更新导航分类显示数量",
  update_navigation_link: "编辑导航网站",
  update_news_category: "编辑新闻分类",
  update_news_post: "编辑新闻",
  update_recycle_bin_news_retention_settings: "更新新闻回收站保留天数",
  update_recycle_bin_retention_settings: "更新回收站保留天数",
  update_report_limit_settings: "更新举报限制设置",
  update_seo_content_section: "更新首页 SEO 内容",
  update_site_setting: "更新站点设置",
  update_top_quick_link: "编辑顶部快捷导航",
  update_user_note: "更新用户备注",
  wrong_category: "分类错误提醒",
};

const entityTypeLabels: Record<string, string> = {
  ad: "广告图片",
  ads: "广告",
  admin_roles: "管理员授权",
  home_banners: "首页 Banner",
  home_sections: "首页模块",
  image_assets: "图片资源",
  latest_ticker: "最新动态",
  navigation_categories: "导航分类",
  navigation_link: "导航网站图片",
  navigation_links: "导航网站",
  news_categories: "新闻分类",
  news_post: "新闻图片",
  news_posts: "新闻",
  notifications: "通知",
  post_reports: "举报",
  posts: "用户发布",
  profiles: "用户资料",
  recycle_bin_news_retention: "新闻回收站设置",
  recycle_bin_retention: "回收站设置",
  site_settings: "站点设置",
  support_tickets: "反馈 / 线索",
  top_quick_links: "顶部快捷导航",
};

export function formatAuditActionLabel(action: string) {
  return actionLabels[action] ?? action;
}

export function formatAuditEntityTypeLabel(entityType: string | null | undefined) {
  if (!entityType) return "未记录对象";
  return entityTypeLabels[entityType] ?? entityType;
}

export function formatAuditOptionLabel(value: string, formatter: (value: string) => string) {
  const label = formatter(value);
  return label === value ? value : `${label}（${value}）`;
}
