insert into public.feature_flags (key, name, description, module, is_enabled, visibility, config)
values
  ('home', '首页', 'Home module.', 'core', true, 'public', '{}'::jsonb),
  ('auth_email', '邮箱登录', 'Email sign up and login.', 'auth', true, 'public', '{}'::jsonb),
  ('auth_google', 'Google 登录', 'Google OAuth login.', 'auth', true, 'public', '{}'::jsonb),
  ('profiles', '用户资料', 'User profile module.', 'users', true, 'public', '{}'::jsonb),
  ('business_profiles_basic', '商家基础资料', 'Basic business profile fields.', 'users', true, 'public', '{}'::jsonb),
  ('jobs', '招聘', 'Jobs channel.', 'posts', true, 'public', '{}'::jsonb),
  ('housing', '房屋', 'Housing channel.', 'posts', true, 'public', '{}'::jsonb),
  ('marketplace', '二手市场', 'Marketplace channel.', 'posts', true, 'public', '{}'::jsonb),
  ('services', '本地服务', 'Local services channel.', 'posts', true, 'public', '{}'::jsonb),
  ('news', '新闻', 'News module.', 'content', true, 'public', '{}'::jsonb),
  ('dmv', 'DMV', 'DMV practice module.', 'dmv', true, 'public', '{}'::jsonb),
  ('navigation', '导航', 'Public and user navigation.', 'navigation', true, 'public', '{}'::jsonb),
  ('search_basic', '基础搜索', 'Basic search module.', 'search', true, 'public', '{}'::jsonb),
  ('favorites', '收藏', 'Post favorites.', 'users', true, 'public', '{}'::jsonb),
  ('recent_views', '最近浏览', 'Recent views.', 'users', true, 'public', '{}'::jsonb),
  ('drafts', '草稿', 'Post drafts.', 'posts', true, 'public', '{}'::jsonb),
  ('feedback', '反馈', 'Feedback module.', 'feedback', true, 'public', '{}'::jsonb),
  ('reports', '举报', 'Report module.', 'moderation', true, 'public', '{}'::jsonb),
  ('notifications_in_app', '站内通知', 'In-app notifications.', 'notifications', true, 'public', '{}'::jsonb),
  ('system_announcements', '系统公告', 'System announcements.', 'notifications', true, 'public', '{}'::jsonb),
  ('ads', '广告', 'Ad placements.', 'operations', true, 'public', '{}'::jsonb),
  ('pwa', 'PWA', 'PWA shell.', 'app', true, 'public', '{}'::jsonb),
  ('seo', 'SEO', 'SEO foundation.', 'seo', true, 'public', '{}'::jsonb),
  ('admin_roles', '后台角色', 'Admin role and permission system.', 'admin', true, 'admin_only', '{}'::jsonb),
  ('image_management', '图片管理', 'Image asset management.', 'media', true, 'admin_only', '{}'::jsonb),
  ('auth_apple', 'Apple 登录', 'Apple login reservation.', 'auth', false, 'hidden', '{}'::jsonb),
  ('auth_wechat', '微信登录', 'WeChat login reservation.', 'auth', false, 'hidden', '{}'::jsonb),
  ('auth_phone', '手机号登录', 'Phone login reservation.', 'auth', false, 'hidden', '{}'::jsonb),
  ('web_push', '浏览器推送', 'Browser Web Push reservation.', 'notifications', false, 'hidden', '{}'::jsonb),
  ('native_push', '原生推送', 'Native push reservation.', 'notifications', false, 'hidden', '{}'::jsonb),
  ('comments', '评论', 'Comments reservation.', 'community', false, 'hidden', '{}'::jsonb),
  ('ratings', '评分', 'Ratings reservation.', 'community', false, 'hidden', '{}'::jsonb),
  ('business_verification', '商家认证', 'Business verification reservation.', 'business', false, 'hidden', '{}'::jsonb),
  ('business_public_pages', '商家主页', 'Business public pages reservation.', 'business', false, 'hidden', '{}'::jsonb),
  ('appointments', '预约', 'Appointment reservation.', 'business', false, 'hidden', '{}'::jsonb),
  ('coupons', '优惠券', 'Coupon reservation.', 'business', false, 'hidden', '{}'::jsonb),
  ('memberships', '会员', 'Membership reservation.', 'commerce', false, 'hidden', '{}'::jsonb),
  ('points', '积分', 'Points reservation.', 'commerce', false, 'hidden', '{}'::jsonb),
  ('payments', '支付', 'Payments reservation.', 'commerce', false, 'hidden', '{}'::jsonb),
  ('orders', '订单', 'Orders reservation.', 'commerce', false, 'hidden', '{}'::jsonb),
  ('chats', '聊天', 'Chat reservation.', 'messaging', false, 'hidden', '{}'::jsonb),
  ('rideshare', '拼车', 'Rideshare reservation.', 'community', false, 'hidden', '{}'::jsonb),
  ('multi_city_public', '多城市前台', 'Public multi-city reservation.', 'cities', false, 'hidden', '{}'::jsonb),
  ('app_deep_links', 'APP 深链', 'App deep link reservation.', 'app', false, 'hidden', '{}'::jsonb),
  ('ad_packages', '广告套餐', 'Ad package reservation.', 'operations', false, 'hidden', '{}'::jsonb)
on conflict (key) do update
set
  name = excluded.name,
  description = excluded.description,
  module = excluded.module,
  is_enabled = excluded.is_enabled,
  visibility = excluded.visibility,
  config = excluded.config,
  updated_at = now();
